### ISSUE TITLE
peer-to-peer code review

### ISSUE THREAD

**Issue by thecodechaser** [Debas-31/dbus-first-capstone#2]
feedbacks, suggestions, improvments

**Comment by thecodechaser** [comment]
## Hello @Debas-31 👋

You did great so far, Your project is already looking great, You probably did hard work for this 👍.

I have some suggestions for you, you can look into these changes 😄.

### Suggested Changes ♻️

- [ ] You can fix navbar menu
Some of the navbar menu items are not working properly, I think you can fix them to improve your project more.

Great job 👍

**Comment by Debas-31** [comment]
Thank you for the feedback. I will implement that.
